ProyectoFinalPolotic/urls.py
from django.contrib import admin
from django.urls import include, path
from proyectofinal import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("proyectofinal.urls")),
    path('productos/', include("productos.urls")),
    path('contacto/', include("contacto.urls")),
    path('carro/', include("carro.urls")),
]

carro/urls.py
from django.urls import path
from . import views
app_name = "carro"
urlpatterns = [
    path("", views.carro, name="carro"),
    path("agregar/<int:producto_id>", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>", views.restar_producto, name="restar"),
    path("limpiar", views.limpiar_carro, name="limpiar"),
]

carro/models.py
from django.db import models

# Create your models here.

carro/views.py
from django.shortcuts import render,redirect
from productos.models import *
from .carro import Carro
# Create your views here.


def agregar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)
    carro.agregar(producto=producto)
    return render(request, "carro/carro.html")

def eliminar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)
    carro.eliminar(producto=producto)
    return render(request, "carro/carro.html")

def restar_producto(request, producto_id):
    carro=Carro(request)
    producto=Productos.objects.get(id=producto_id)
    carro.restar_producto(producto=producto)
    return render(request, "carro/carro.html")

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return render(request, "carro/carro.html")



def carro(request):
    return render(request, "carro/carro.html")

carro/templates/carro/carro.html
{% extends "proyectofinal/layout.html"%}

{% block body%}

<table class="table table-bordered" style="color:black" ;>

    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carro de compras
            </th>
        </tr>

        <tr>
            <th>
                Producto
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Suma
            </th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}

        {% for key, value in request.session.carro.items %}
        <tr class="text-center">
            <td>
                {{value.nombre}}
            </td>
            <td>
                {{value.cantidad}}
            </td>
            <td>
                <a href="{% url 'carro:agregar' value.producto_id%}" class="btn btn-sm btn-success">+</a>
                <a href="{% url 'carro:restar' value.producto_id%}" class="btn btn-sm btn-success">-</a>
                $ {{value.precio}}

            </td>
        </tr>
        {% endfor %}

        {% else %}
        <tr>
            <td colspan="3">
                <div class="alert alert-warning text-center">Sin productos</div>
            </td>
        </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="1">
                Total: $ {{importe_total_carro}}

            </td>
            <td>
                <div class=text-center>
                    <a href="{% url 'carro:limpiar' %}" class="btn btn-danger">Vaciar carro</a>
                </div>
            </td>
            <td>
                <div class=text-center>
                    <a href="{% url 'index' %}" class="btn btn-primary">Finalizar compra</a>
                </div>
            </td>
        </tr>
    </tfoot>
</table>

<!-- <ul class="list-group">
    <li class="list-group-item">PRODUCTO 1</li>
    <li class="list-group-item">PRODUCTO 2</li>
    <li class="list-group-item">PRODUCTO 3</li>
    <li class="list-group-item">PRODUCTO 4</li>
    <li class="list-group-item">PRODUCTO 5</li>
    <li class="list-group-item">PRECIO TOTAL: ${{importe_total_carro}}</li>
</ul> -->
{% endblock %}